#!/bin/bash
cd /tmp/rom # Depends on where source got synced

sudo apt-get -y update && sudo apt-get -y upgrade && sudo apt-get -y install git bc build-essential zip curl libstdc++6 git wget python python2 gcc clang libssl-dev openssl repo rsync flex bison gcc-aarch64-linux-gnu
git config --global user.name "phoenix-1708"
git config --global user.email "harikumar1708@gmail.com"
git config --global color.ui true


# mkdir -p /tmp/rom # Where to sync source
# cd /tmp/rom
git clone https://github.com/akhilnarang/scripts && cd scripts && bash setup/android_build_env.sh && cd ..

mkdir phoenix
cd phoenix

wget https://raw.githubusercontent.com/phoenix-1708/PE_Kernel/eleven/.circleci/build.sh
source build.sh
